### ISSUE TITLE
yahoo login not working

### ISSUE THREAD

**Issue by tinio** [codeforamerica/prepared.ly#14]
https://skitch.com/tinio/825p7/

**Comment by joemerante** [comment]
This one didn't work because the callback got sent to http://www.prepared.ly... Yahoo only allows you to register one url per app, so the app is currently set up to work only with http://signup.prepared.ly.  If you go in via signup.prepared.ly it works fine.  Let me know when you remove the redirect of prepared.ly to signup.prepared.ly and I'll create a new Yahoo app and add those keys to Heroku. Yahoo doesn't let you edit the app's url once it's created either :(

**Comment by joemerante** [comment]
This seems to work fine now even with the staging subdomain, so long as the prepared.ly is there.  Not sure why it didn't work for you yesterday..

**Comment by tinio** [comment]
I take it that you created a new yahoo app? Hence, why it didn't work yesterday?

**Comment by joemerante** [comment]
Nope, didn't create a new one.  It worked yesterday too, just not with a 'www' prefix which you were accessing with (noticed in Skitch images).  I just checked, and the current app is set up to use http://prepared.ly, so either that or http://staging.prepared.ly will work fine.  If/when we add a www prefix to the url (http://www.prepared.ly), not sure if will still work as expected.  Have you tried it again?

**Comment by tinio** [comment]
Just tried it again and it's still broken:

https://skitch.com/tinio/83dbq/

Reopening the issue.

**Comment by joemerante** [comment]
OK, let's take a look at this tomorrow, I'll leave the issue open.  I just tried authenticating using Yahoo on both http://prepared.ly and http://www.prepared.ly and both worked fine.

**Comment by joemerante** [comment]
Seems to have worked consistently in Production for the past two months..
